2015-03-21 11:31:16,706 - [INFO] - from play in pool-8-thread-2 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2015-03-21 11:31:29,132 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2015-03-21 11:44:09,510 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2015-03-21 11:44:57,260 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2015-03-21 11:45:21,459 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2015-03-21 11:47:28,131 - [ERROR] - from application in New I/O worker #7 


! @6lh4bif16 - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value content]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49) ~[na:na]
	at play.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
	at play.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
	at play.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at play.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$.compile(PlayReload.scala:17) ~[na:na]
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61) ~[na:na]
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61) ~[na:na]
	at play.runsupport.Reloader.reload(Reloader.scala:295) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2015-03-21 11:48:20,525 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 11:49:17,403 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 11:58:04,242 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 11:59:03,647 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 11:59:37,096 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 12:01:48,034 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 12:03:33,331 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 12:03:59,075 - [ERROR] - from application in New I/O worker #4 


! @6lh4dmooh - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[play.twirl.api.Html does not take parameters]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49) ~[na:na]
	at play.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
	at play.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
	at play.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at play.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$.compile(PlayReload.scala:17) ~[na:na]
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61) ~[na:na]
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61) ~[na:na]
	at play.runsupport.Reloader.reload(Reloader.scala:295) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2015-03-21 12:05:02,076 - [ERROR] - from application in New I/O worker #4 


! @6lh4e0e3l - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value conten]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49) ~[na:na]
	at play.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
	at play.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
	at play.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at play.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$.compile(PlayReload.scala:17) ~[na:na]
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61) ~[na:na]
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61) ~[na:na]
	at play.runsupport.Reloader.reload(Reloader.scala:295) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2015-03-21 12:05:25,939 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 12:11:35,013 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 12:12:34,874 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 12:15:13,681 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 12:16:19,535 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 12:23:31,287 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 12:52:31,825 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 12:52:45,306 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 12:52:52,285 - [INFO] - from play in play-internal-execution-context-9 
Application started (Dev)

2015-03-21 12:52:58,578 - [INFO] - from play in play-internal-execution-context-9 
Application started (Dev)

2015-03-21 12:53:04,035 - [INFO] - from play in play-internal-execution-context-9 
Application started (Dev)

2015-03-21 12:53:09,751 - [INFO] - from play in play-internal-execution-context-9 
Application started (Dev)

2015-03-21 13:08:57,650 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 13:10:32,925 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-03-21 13:11:19,081 - [INFO] - from play in play-internal-execution-context-10 
Application started (Dev)

2015-03-21 13:14:28,441 - [INFO] - from play in play-internal-execution-context-12 
Application started (Dev)

2015-03-21 13:29:01,797 - [INFO] - from play in play-internal-execution-context-13 
Application started (Dev)

2015-03-21 14:07:50,486 - [INFO] - from play in play-internal-execution-context-13 
Application started (Dev)

2015-03-21 14:08:12,998 - [INFO] - from play in play-internal-execution-context-13 
Application started (Dev)

2015-03-21 14:18:47,168 - [INFO] - from play in play-internal-execution-context-13 
Application started (Dev)

2015-03-21 15:00:01,665 - [INFO] - from play in play-internal-execution-context-28 
Application started (Dev)

2015-03-21 15:22:45,435 - [INFO] - from play in play-internal-execution-context-36 
Application started (Dev)

2015-03-21 15:28:08,414 - [INFO] - from play in play-internal-execution-context-36 
Application started (Dev)

2015-03-21 15:32:58,175 - [INFO] - from play in play-internal-execution-context-36 
Application started (Dev)

2015-03-21 15:33:36,010 - [INFO] - from play in play-internal-execution-context-40 
Application started (Dev)

2015-03-21 15:34:14,075 - [INFO] - from play in play-internal-execution-context-40 
Application started (Dev)

2015-03-21 15:34:52,708 - [INFO] - from play in play-internal-execution-context-40 
Application started (Dev)

2015-03-21 15:48:32,666 - [INFO] - from play in play-internal-execution-context-40 
Application started (Dev)

2015-03-21 16:10:55,849 - [ERROR] - from application in New I/O worker #14 


! @6lh5k7p6f - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[value show is not a member of object controllers.FailureController]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49) ~[na:na]
	at play.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
	at play.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
	at play.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at play.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReload$.compile(PlayReload.scala:17) ~[na:na]
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61) ~[na:na]
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61) ~[na:na]
	at play.runsupport.Reloader.reload(Reloader.scala:295) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2015-03-21 16:11:23,562 - [INFO] - from play in play-internal-execution-context-40 
Application started (Dev)

2015-03-21 16:40:57,851 - [INFO] - from play in play-internal-execution-context-50 
Application started (Dev)

2015-03-21 16:44:24,576 - [INFO] - from play in play-internal-execution-context-50 
Application started (Dev)

2015-03-21 16:48:35,264 - [INFO] - from play in play-internal-execution-context-50 
Application started (Dev)

2015-03-21 16:54:04,898 - [INFO] - from play in play-internal-execution-context-52 
Application started (Dev)

2015-03-21 16:55:18,456 - [INFO] - from play in play-internal-execution-context-52 
Application started (Dev)

2015-03-21 16:56:01,814 - [INFO] - from play in play-internal-execution-context-52 
Application started (Dev)

